# Generated by Django 3.2 on 2022-02-22 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media.fields
import media.storage.local


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_type",
                    models.CharField(default="music", max_length=5),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="artist",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="title",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="genre",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="size"
                    ),
                ),
                (
                    "length",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="length"
                    ),
                ),
                (
                    "file",
                    media.fields.AudioField(
                        max_length=255,
                        storage=media.storage.local.Storage(
                            directory_structure=(2, 2), prefix="audio_tracks"
                        ),
                        upload_to="",
                    ),
                ),
                ("file_name", models.CharField(max_length=256)),
                ("file_hash", models.CharField(max_length=40)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
